fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    concat: 'puppetlabs-concat'
    apt: 'puppetlabs-apt'
    docker: 'garethr/docker'
  symlinks:
    gitlab_ci_multi_runner: "#{source_dir}"
