---
language: ruby
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2
notifications:
    email: false
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="3.8.7"
  - PUPPET_GEM_VERSION="4.0"
  - PUPPET_GEM_VERSION="4.1"
matrix:
    exclude:
        - rvm: 2.2
          env: PUPPET_GEM_VERSION="3.8.7"

